const GET_STYLIST_BY_ID_PENDING = 'GET_STYLIST_BY_ID_PENDING'
const GET_STYLIST_BY_ID_FULFILLED = 'GET_STYLIST_BY_ID_FULFILLED'
const GET_STYLIST_BY_ID_REJECTED = 'GET_STYLIST_BY_ID_REJECTED'
const GET_STYLIST_SEVICE_BY_ID_PENDING = 'GET_STYLIST_SEVICE_BY_ID_PENDING'
const GET_STYLIST_SEVICE_BY_ID_FULFILLED = 'GET_STYLIST_SEVICE_BY_ID_FULFILLED'
const GET_STYLIST_SEVICE_BY_ID_REJECTED = 'GET_STYLIST_SEVICE_BY_ID_REJECTED'
const GET_STYLIST_OPEN_HOURS = 'GET_STYLIST_OPEN_HOURS'

export {
  GET_STYLIST_OPEN_HOURS,
  GET_STYLIST_BY_ID_PENDING, 
  GET_STYLIST_BY_ID_FULFILLED, 
  GET_STYLIST_BY_ID_REJECTED,
  GET_STYLIST_SEVICE_BY_ID_PENDING,
  GET_STYLIST_SEVICE_BY_ID_FULFILLED,
  GET_STYLIST_SEVICE_BY_ID_REJECTED
}
