const CREATE_SERVICE_PENDING = 'CREATE_SERVICE_PENDING'
const CREATE_SERVICE_FULFILLED = 'CREATE_SERVICE_FULFILLED'
const CREATE_SERVICE_REJECTED = 'CREATE_SERVICE_REJECTED'

const GET_SERVICE_BY_ID_PENDING = 'GET_SERVICE_BY_ID_PENDING'
const GET_SERVICE_BY_ID_FULFILLED = 'GET_SERVICE_BY_ID_FULFILLED'
const GET_SERVICE_BY_ID_REJECTED = 'GET_SERVICE_BY_ID_REJECTED'

const GET_STYLIST_SERVICES_PENDING = 'GET_STYLIST_SERVICES_PENDING'
const GET_STYLIST_SERVICES_FULFILLED = 'GET_STYLIST_SERVICES_FULFILLED'
const GET_STYLIST_SERVICES_REJECTED = 'GET_STYLIST_SERVICES_REJECTED'

const UPDATE_SERVICE_BY_ID_PENDING = 'UPDATE_SERVICE_BY_ID_PENDING'
const UPDATE_SERVICE_BY_ID_FULFILLED = 'UPDATE_SERVICE_BY_ID_FULFILLED'
const UPDATE_SERVICE_BY_ID_REJECTED = 'UPDATE_SERVICE_BY_ID_REJECTED'

const DELETE_SERVICE_BY_ID_PENDING = 'DELETE_SERVICE_BY_ID_PENDING'
const DELETE_SERVICE_BY_ID_FULFILLED = 'DELETE_SERVICE_BY_ID_FULFILLED'
const DELETE_SERVICE_BY_ID_REJECTED = 'DELETE_SERVICE_BY_ID_REJECTED'

export {
  CREATE_SERVICE_PENDING,
  CREATE_SERVICE_FULFILLED,
  CREATE_SERVICE_REJECTED,
  GET_SERVICE_BY_ID_PENDING,
  GET_SERVICE_BY_ID_FULFILLED,
  GET_SERVICE_BY_ID_REJECTED,
  GET_STYLIST_SERVICES_PENDING,
  GET_STYLIST_SERVICES_FULFILLED,
  GET_STYLIST_SERVICES_REJECTED,
  UPDATE_SERVICE_BY_ID_PENDING,
  UPDATE_SERVICE_BY_ID_FULFILLED,
  UPDATE_SERVICE_BY_ID_REJECTED,
  DELETE_SERVICE_BY_ID_PENDING,
  DELETE_SERVICE_BY_ID_FULFILLED,
  DELETE_SERVICE_BY_ID_REJECTED
}
