const CREATE_REVIEW_PENDING = 'CREATE_REVIEW_PENDING'
const CREATE_REVIEW_FULFILLED = 'CREATE_REVIEW_FULFILLED'
const CREATE_REVIEW_REJECTED = 'CREATE_REVIEW_REJECTED'

const GET_REVIEWS_PENDING = 'GET_REVIEWS_PENDING'
const GET_REVIEWS_FULFILLED = 'GET_REVIEWS_FULFILLED'
const GET_REVIEWS_REJECTED = 'GET_REVIEWS_REJECTED'

const GET_REVIEW_BY_ID_PENDING = 'GET_REVIEW_BY_ID_PENDING'
const GET_REVIEW_BY_ID_FULFILLED = 'GET_REVIEW_BY_ID_FULFILLED'
const GET_REVIEW_BY_ID_REJECTED = 'GET_REVIEW_BY_ID_REJECTED'

const UPDATE_REVIEW_BY_ID_PENDING = 'UPDATE_REVIEW_BY_ID_PENDING'
const UPDATE_REVIEW_BY_ID_FULFILLED = 'UPDATE_REVIEW_BY_ID_FULFILLED'
const UPDATE_REVIEW_BY_ID_REJECTED = 'UPDATE_REVIEW_BY_ID_REJECTED'

const REPLACE_REVIEW_BY_ID_PENDING = 'REPLACE_REVIEW_BY_ID_PENDING'
const REPLACE_REVIEW_BY_ID_FULFILLED = 'REPLACE_REVIEW_BY_ID_FULFILLED'
const REPLACE_REVIEW_BY_ID_REJECTED = 'REPLACE_REVIEW_BY_ID_REJECTED'

const DELETE_REVIEW_BY_ID_PENDING = 'DELETE_REVIEW_BY_ID_PENDING'
const DELETE_REVIEW_BY_ID_FULFILLED = 'DELETE_REVIEW_BY_ID_FULFILLED'
const DELETE_REVIEW_BY_ID_REJECTED = 'DELETE_REVIEW_BY_ID_REJECTED'

export {
  CREATE_REVIEW_PENDING,
  CREATE_REVIEW_FULFILLED,
  CREATE_REVIEW_REJECTED,
  GET_REVIEWS_PENDING,
  GET_REVIEWS_FULFILLED,
  GET_REVIEWS_REJECTED,
  GET_REVIEW_BY_ID_PENDING,
  GET_REVIEW_BY_ID_FULFILLED,
  GET_REVIEW_BY_ID_REJECTED,
  UPDATE_REVIEW_BY_ID_PENDING,
  UPDATE_REVIEW_BY_ID_FULFILLED,
  UPDATE_REVIEW_BY_ID_REJECTED,
  REPLACE_REVIEW_BY_ID_PENDING,
  REPLACE_REVIEW_BY_ID_FULFILLED,
  REPLACE_REVIEW_BY_ID_REJECTED,
  DELETE_REVIEW_BY_ID_PENDING,
  DELETE_REVIEW_BY_ID_FULFILLED,
  DELETE_REVIEW_BY_ID_REJECTED
}
