const CREATE_OPEN_HOURS_PENDING = 'CREATE_OPEN_HOURS_PENDING'
const CREATE_OPEN_HOURS_FULFILLED = 'CREATE_OPEN_HOURS_FULFILLED'
const CREATE_OPEN_HOURS_REJECTED = 'CREATE_OPEN_HOURS_REJECTED'

const GET_OPEN_HOURS_PENDING = 'GET_OPEN_HOURS_PENDING'
const GET_OPEN_HOURS_FULFILLED = 'GET_OPEN_HOURS_FULFILLED'
const GET_OPEN_HOURS_REJECTED = 'GET_OPEN_HOURS_REJECTED'

const GET_OPEN_HOURS_BY_ID_PENDING = 'GET_OPEN_HOURS_BY_ID_PENDING'
const GET_OPEN_HOURS_BY_ID_FULFILLED = 'GET_OPEN_HOURS_BY_ID_FULFILLED'
const GET_OPEN_HOURS_BY_ID_REJECTED = 'GET_OPEN_HOURS_BY_ID_REJECTED'

export {
  CREATE_OPEN_HOURS_PENDING,
  CREATE_OPEN_HOURS_FULFILLED,
  CREATE_OPEN_HOURS_REJECTED,
  GET_OPEN_HOURS_PENDING,
  GET_OPEN_HOURS_FULFILLED,
  GET_OPEN_HOURS_REJECTED,
  GET_OPEN_HOURS_BY_ID_PENDING,
  GET_OPEN_HOURS_BY_ID_FULFILLED,
  GET_OPEN_HOURS_BY_ID_REJECTED
}
