const GET_USER_BY_ID_PENDING = 'GET_USER_BY_ID_PENDING'
const GET_USER_BY_ID_FULFILLED = 'GET_USER_BY_ID_FULFILLED'
const GET_USER_BY_ID_REJECTED = 'GET_USER_BY_ID_REJECTED'

const UPDATE_USER_BY_ID_PENDING = 'UPDATE_USER_BY_ID_PENDING'
const UPDATE_USER_BY_ID_FULFILLED = 'UPDATE_USER_BY_ID_FULFILLED'
const UPDATE_USER_BY_ID_REJECTED = 'UPDATE_USER_BY_ID_REJECTED'

const DELETE_USER_BY_ID_PENDING = 'DELETE_USER_BY_ID_PENDING'
const DELETE_USER_BY_ID_FULFILLED = 'DELETE_USER_BY_ID_FULFILLED'
const DELETE_USER_BY_ID_REJECTED = 'DELETE_USER_BY_ID_REJECTED'

export {
  GET_USER_BY_ID_PENDING,
  GET_USER_BY_ID_FULFILLED,
  GET_USER_BY_ID_REJECTED,
  UPDATE_USER_BY_ID_PENDING,
  UPDATE_USER_BY_ID_FULFILLED,
  UPDATE_USER_BY_ID_REJECTED,
  DELETE_USER_BY_ID_PENDING,
  DELETE_USER_BY_ID_FULFILLED,
  DELETE_USER_BY_ID_REJECTED
}
