const CREATE_LOCATION_PENDING = 'CREATE_LOCATION_PENDING'
const CREATE_LOCATION_FULFILLED = 'CREATE_LOCATION_FULFILLED'
const CREATE_LOCATION_REJECTED = 'CREATE_LOCATION_REJECTED'

const GET_LOCATION_BY_ID_PENDING = 'GET_LOCATION_BY_ID_PENDING'
const GET_LOCATION_BY_ID_FULFILLED = 'GET_LOCATION_BY_ID_FULFILLED'
const GET_LOCATION_BY_ID_REJECTED = 'GET_LOCATION_BY_ID_REJECTED'

const GET_ADDRESS_BY_COORDS_FULFILLED = 'GET_ADDRESS_BY_COORDS_FULFILLED'
const GET_ADDRESS_BY_COORDS_REJECTED = 'GET_ADDRESS_BY_COORDS_REJECTED'
const SET_GOOGLE_ADDRESS_COMPONENTS = 'SET_GOOGLE_ADDRESS_COMPONENTS'
const SET_GOOGLE_COORDS = 'SET_GOOGLE_COORDS'

export {
  CREATE_LOCATION_PENDING,
  CREATE_LOCATION_FULFILLED,
  CREATE_LOCATION_REJECTED,
  GET_LOCATION_BY_ID_PENDING,
  GET_LOCATION_BY_ID_FULFILLED,
  GET_LOCATION_BY_ID_REJECTED,
  GET_ADDRESS_BY_COORDS_FULFILLED,
  GET_ADDRESS_BY_COORDS_REJECTED,
  SET_GOOGLE_COORDS,
  SET_GOOGLE_ADDRESS_COMPONENTS
}
