const REGISTER_PENDING = 'REGISTER_PENDING'
const REGISTER_FULFILLED = 'REGISTER_FULFILLED'
const REGISTER_REJECTED = 'REGISTER_REJECTED'

const BUSINESS_REGISTER_PENDING = 'BUSINESS_REGISTER_PENDING'
const BUSINESS_REGISTER_FULFILLED = 'BUSINESS_REGISTER_FULFILLED'
const BUSINESS_REGISTER_REJECTED = 'BUSINESS_REGISTER_REJECTED'

const SET_BUSINESS_LOCATION = 'SET_BUSINESS_LOCATION'
const SET_BUSINESS_SERVICES = 'SET_BUSINESS_SERVICES'
const SET_BUSINESS_OPENING_HOURS = 'SET_BUSINESS_OPENING_HOURS'
const SET_FB_DATA = 'SET_FB_DATA'

const LOGIN_PENDING = 'LOGIN_PENDING'
const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
const FACEBOOK_LOGIN_FULFILLED = 'FACEBOOK_LOGIN_FULFILLED'
const LOGIN_REJECTED = 'LOGIN_REJECTED'
const SET_LOCAL_DATA = 'SET_LOCAL_DATA'
const SET_REGISTER_LINK = 'SET_REGISTER_LINK'
const LOGOUT = 'LOGOUT'

export {
  REGISTER_PENDING,
  REGISTER_FULFILLED,
  SET_REGISTER_LINK,
  REGISTER_REJECTED,
  BUSINESS_REGISTER_PENDING,
  BUSINESS_REGISTER_FULFILLED,
  BUSINESS_REGISTER_REJECTED,
  SET_BUSINESS_LOCATION,
  SET_BUSINESS_SERVICES,
  SET_BUSINESS_OPENING_HOURS,
  LOGIN_PENDING,
  LOGIN_FULFILLED,
  FACEBOOK_LOGIN_FULFILLED,
  LOGIN_REJECTED,
  LOGOUT,
  SET_LOCAL_DATA,
  SET_FB_DATA
}
