const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT'
const CREATE_APPOINTMENT_FULFILLED = 'CREATE_APPOINTMENT_FULFILLED'
const CREATE_APPOINTMENT_REJECTED = 'CREATE_APPOINTMENT_REJECTED'
const SET_DATE_FROM_MODAL = 'SET_DATE_FROM_MODAL'
const SET_TIME_FROM_MODAL = 'SET_TIME_FROM_MODAL'

export {
  CREATE_APPOINTMENT,
  CREATE_APPOINTMENT_FULFILLED,
  CREATE_APPOINTMENT_REJECTED,
  SET_DATE_FROM_MODAL,
  SET_TIME_FROM_MODAL
}
